### ISSUE TITLE
Term kennt nur Semester

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#13]
Autor: Arn Waßmann
Art der Organisation: HIS Hochschul-Informations-System eG
Beschreibung: 

Liebe Kolleginnen und Kollegen,

ich möchte darauf Hinweisen, dass es neben Hochschulen mit Semestern auch Hochschulen mit Trimestern und sogar Quartalen gibt. Auch ein Studienjahr muss abgebildet werden können. Die aktuell zur Verfügung gestellte Wertemenge ist somit nicht ausreichend.

http://xhochschule.de/def/xhochschule/0.6/code/semester/

Beispiele aus HISinOne:

**Termcategory**
Studienjahr, Semester, Trimester, Studienquartal

**Termnumber**
Sommersemester, Wintersemester, Wintertrimester, Frühjahrestrimester, Herbsttrimester 

Viele Grüße
Arn Waßmann

**Comment by init-xhochschule** [comment]
Wird bearbeitet in Issue Nr.  [**27**](https://github.com/OZG-TFBildung/XHochschule/issues/27).
Für welchen Zweck (bzw. expliziten Datenaustausch) welche Periodenlängen benötigt werden befindet sich derzeit in Klärung.
