### ISSUE TITLE
Inhaltliche Bedeutung diplomaSupplement -> dauerUndEbeneQualifikation -> zugangsvorraussetzungen

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#14]
Autor: Arn Waßmann | HIS eG
Art der Organisation: CaMS-Hersteller
Beschreibung:

Guten Tag,

es geht um die Spezifikation 0.8.

Beim _diplomaSupplement_ gibt es  das Kindelement _dauerUndEbeneQualifikation_ und die beiden Attribute  _zugangsvorraussetzungen_ und _zugangsvorraussetzungenErgaenzung_. Wir möchten gerne verstehen warum und wofür diese Werte hier aufgenommen wurden. 

Es bereitet uns etwas Kopfzerbrechen wie diese Felder sinnvoll gefüllt werden könnten. Beim Attribute _zugangsvorraussetzungen_ wird auf _Code.ArtDerHZB_ referenziert, die sich aus den Werten der amtlichen Statistik speist. Die Werte wiederum sind motiviert durch den Zugang zu einem grundständigen Studiengang und da auch nur der schulische Teil. Ist es tatsächlich so gedacht, dass hier die Werte, welche auch an die amtliche Statistik geliefert werden, nochmals aufgeführt werden? Sollen nicht vorhandene HZBen in das Freitextfeld _zugangsvorraussetzungenErgaenzung_ gefüllt werden? Darunter fallen bspw. die seit Jahren gelöschten HZBen _35 - Abschluss oder Zwischenprüfung an einer Fachhochschule (aHR)_ und _46 - Abschluss oder Zwischenprüfung an einer Fachhochschule (fgHR)_, die aber natürlich noch existieren, aber nur nicht mehr erfasst werden, und alle Formen von Hochschulabschlüssen selbst. Auch ein Hochschulabschluss kann eine HZB sein, bspw. für den Zugang zu einem weiterführenden Studiengang. Spätestens dann würde das Freitextfeld immer verwendet werden. Ist das tatsächlich so gemeint?

Was fängt eine konsumierende Stelle mit diesen Werten an? Was wäre ein Beispiel dafür?

Vielen Dank und beste Grüße
Arn Waßmann

**Comment by OZG-TFBildung** [comment]
Guten Tag,

vielen Dank für das wertvolle Feedback. 

Ziel bei der Erstellung des Diploma Supplemets in der Version 0.8 war es bisher, möglichst viele der standardisierten Abschnitte als strukturierte Daten zu modellieren, die bereits mit XHochschule erfassbar sind. Dadurch sollten diejenige, der ein Diploma Supplement auswerten, möglichst selten Freitexte überprüfen müssen. So soll ein Mehrwert gegenüber dem reinen Freitextansatz (wie z.B. in ELMO) geschaffen werden.

Im Attribut _zugangsverraussetzung_ wäre dementsprechend der Code aus _Code.ArtDerHZB_ aufzuführen, der eine Voraussetzung für die Aufnahme des Studiums darstellte, unabhängig davon, ob die Werte bereits im Rahmen der amtlichen Statistik genutzt wurden.

Als Prüffrage hatten wir zu diesem Attribut bereits festgehalten:

> Sind die Werte von "ArtDerHZB" überschneidungsfrei?
> Also gibt es einen "höchsten" der angegeben werden kann?
> Wenn ja, Beschreibung präzisieren. Wenn nein: Kardinalität 0..n.

Ihre Beispiele zeigen gut, dass diese Codeliste alleine nicht genügt. Ob man mehrere Codelisten erlaubt, eine andere nutzen könnte, eine neue anlegen müsste oder doch auf Freitext zurückgreifen sollte, ist nicht nur für dieses Attribut zu klären. Daher wollen wir demnächst mit den Stakeholdern in einem Arbeitskreis klären, wo sonst noch im Diploma Supplement strukturierte Daten fachlich sinnvoll für den Datenaustausch sind und wie diese zu strukturieren sind.

Viele Grüße
Ludger Rinsche

**Comment by ArnWassmann** [comment]
Hallo Herr Rinsche,

in unseren Diploma Supplements (DS), die wir als PDF's ausgeben und aus der HISinOne-Datenbank generieren, sind die allgemeinen Zulassungsvoraussetzungen für den Studiengang enthalten. Es sind ausdrücklich nicht die persönlichen Qualifikationen des Studierenden, die zur Zulassung geführt hatten. Es handelt sich um ein Freitextfeld in dem die Hochschulen die Voraussetzungen beschreiben. 

Im Rahmen der Studienplatzbewerbung sind diese Voraussetzungen natürlich formal abgebildet und werden auch individuell erfasst. Nach erfolgreicher Studienplatzbewerbung werden diese persönlichen Daten der Bewerbenden aber wieder gelöscht und nicht ins Studierendenmanagement übernommen. Bisher wurden diese Daten auch nicht benötigt und der Datenschutz gebietet hier somit die Löschung. Die formalen Voraussetzungen der Studienplatzbewerbung werden nicht bei der Generierung des DS im Rahmen des Studienabschlusses verwendet.

Nach unserer Einschätzung ist _Code.ArtDerHZB_  im Diploma Supplement inhaltlich unangemessen. Wir bitten daher um Löschung. Wir plädieren aktuell für ein Freitextfeld. Siehe dazu bitte auch https://europa.eu/europass/de/diploma-supplement und https://europa.eu/europass/en/diploma-supplement-examples

Genauer: https://europa.eu/europass/system/files/2021-10/DS_DE_0.pdf --> 3.3 Zugangsvorraussetzung(en) ließe sich mit dem Datenmodell wohl so nicht abbilden.

Welcher Anwendungsfall steckt hinter diesem Feld? Was macht eine konsumierende Stelle damit eigentlich genau? Abhängig davon sollte die Wahl (Schlüssel vs. Freitext) getroffen werden.

Vielen Dank und beste Grüße
Arn Waßmann

**Comment by init-xhochschule** [comment]
Update: Inzwischen gab es für die Version XHS 0.95 die folgende Änderungen bzgl. des Diploma Supplements (siehe Versionshistorie der aktuellen Spezifikation) https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf

III.E.1.3.1. Überarbeitung des "Diploma Supplement"

Das Diploma Supplement wurde entsprechend der Vorgaben der HRK (HRK Diploma Supplement) überarbeitet und referenziert in den Beschreibungen der Datenfelder die jeweiligen Sektionen des HRKDokuments. Optional wird die Möglichkeit einer Signatur sowie die direkte Einbindung in das Hochschulabschlusszeugnis angeboten. Um den internationalen Austausch zu erleichtern, wurden Datenfelder als Freitext modelliert und kleinere Anpassungen der Datenfelder vorgenommen.

Viele Grüße
Ihr Team von XHochschule
