### ISSUE TITLE
Exma-Besch: Sinn und Zweck von xbd:sprache

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#17]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Bedeutung unklar
**Betroffenes Feld:** xbd:sprache

**Beschreibung:**
Uns ist unklar wofür <xbd:sprache> benötigt wird. Welche Aussage soll dieses Element treffen? Einzelne Elemente, wie bspw. Titel oder Studienfach, enthalten bereits die Sprache. Wir denken, dass dieses Element an dieser Stelle überflüssig ist.

**Comment by XHochschuleDE** [comment]
Hallo Herr Wassmann,

Mit dem Attribut xbd:sprache, welches aus xbd:dokument geerbt wird, kann ausgedrückt werden, in welcher Sprache ein Dokument verfasst wurde. Hierbei könnte z.B. der Wert "DE-CH" mitteilen, dass es sich um Schweitzer Deutsch handelt, wobei dies möglicherweise nicht aus dem Text selbst offensichtlich ist. Die Sprache des Titels bzw. des Studienfachs kann von der Sprache des Dokuments abweichen, bzw. es können mehrere Titel in verschiedenen Sprachen angegeben werden. 

Viele Grüße
Robin Dietrich
