### ISSUE TITLE
Selbstverständnis von XHEIE im EU-Umfeld - PR vs. Sprache der Elementnamen

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#18]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

Laut der Webseite http://www.xhochschule.de ist XHEIE Folgendes: "Es verfolgt das Ziel, den Austausch von Studierendendaten im **nationalen** Hochschulwesen zu vereinheitlichen, sodass die erforderliche Interoperabilität zwischen den Hochschulsystemen (Campus Management Systeme genannt) zur medienbruchfreien Abwicklung von zukünftig digitalen Verwaltungsleistungen hergestellt werden kann." (abgerufen am 28.02.22) 
^^ So würde ich das auch sehen.

Das [XHochschule Animationsvideo](https://www.youtube.com/watch?v=c3P4dU6hAYU) illustriert den fachlichen Bedarf einer solchen Spezifikation im Hochschulwesen (abgerufen am 28.02.22) 
^^ Das Animationsvideo widerspricht der oben zitierten Aussage und führt in der Hochschulwelt immer wieder zu Irritationen, da suggeriert wird, dass es sich um einen EU-Standard handelt. Amélie wechselt von Frankreich nach Deutschland. Dieser Fall wird von XHEIE nicht betrachtet und die Hochschulen haben auch zukünftig für den internationalen Hochschulwechsel keine Unterstützung durch XHEIE. Dies muss von XHochschule klar gestellt werden. Aktuell machen wir das auf Nachfrage der Hochschulen - immer wieder. Das hinterlässt bei den Hochschulen ein ungutes Gefühl (Transparenz) und ist für die Akzeptanz eines neues Standards nicht förderlich. 

Sollte dem nicht so sein, dann müssen alle Elementnamen auf englisch umgestellt werden! Ich behaupte, dass keine Hochschule außerhalb des deutschsprachigen Raums eine XHEIE-Nachricht mit deutschen Elementnamen verstehen und erzeugen wird. Die international anerkannte Sprache in der IT ist englisch.

**Comment by init-xhochschule** [comment]
Danke für den Hinweis zu diesem Missverständnis.  

Der Fokus von XHochschule liegt in der Tat auf dem Austausch von Studierendendaten im deutschen Hochschulraum. Nach der bisherigen Beobachtung und Analyse von existierenden EU-Spezifikationen im Bildungswesen hat sich im Laufe der Zeit zudem herausgestellt, dass XHochschule die EU-weite Interoperabilität natürlich weiterhin als Aufgabe sieht, aber die Herstellung dieser Interoperabilität tatsächlich nicht durch die eigene Spezifikation XHochschule verfolgt, sondern in erster Linie durch Mappings von Codelisten zwischen deutscher und EU-Ebene sowie durch die Einbringung von Anforderungen in diese Vorhaben. 

Die Diskrepanz zwischen dem ursprünglichen Animationsvideo und dem inzwischen klaren Fokus von XHochschule ist in der Tat aktuell noch ein Problem, da der nationale Fokus von XHochschule darin nicht ausreichend klar wird. Daher werden wir demnächst sowohl den Fokus von XHochschule in der Spezifikation also auch auf der Website weiter präzisieren und auch das bisherige Animationsvideo entweder dahingehend überarbeiten oder zunächst offline stellen.

**Comment by XHochschuleDE** [comment]
Hallo Herr Wassmann, 

das Animationsvideo wurde inzwischen auch angepasst, da neue Video ist unter diesem Link https://www.youtube.com/watch?v=dPkTbENMl_E
