### ISSUE TITLE
Exma-Besch: xbd:ausstellung -> xbd:ort

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#19]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Bedeutung unklar
**Betroffenes Feld:** xbd:ausstellung -> xbd:ort

**Beschreibung:**
Viele Hochschulen verfügen über mehrere Standorte. Manche dieser Hochschulen verwenden immer den Ort des Hauptsitzes, andere den des Standortes an der Studierende sich maßgeblich aufhält. Sollte unkritisch sein, wenn dieser Info keine weitere Bedeutung beim Import beigemessen wird. Für eine elektronische Nachricht ist der Ort eigentlich auch irrelevant. Daher kann auch auf dieses Datenfeld verzichtet werden.

**Comment by XHochschuleDE** [comment]
Hallo Herr Wassmann,

Der Ort der Ausstellung eines Bildungsnachweises wird von XSchule für das Abiturzeugnis benötigt. Da die Klasse xbd:ausstellung Teil von xbd:dokument ist, wird dieses Element auch an die Exmatrikulationsbescheinigung vererbt.
Wir haben diesbezüglich auch Anfragen erhalten den Ort der Ausstellung noch mit Angaben zum Erwerb (Ort, Gemeindeschlüssel, Datum) zu komplettieren. (Siehe auch Anforderungen der SfH an ELMO: https://github.com/emrex-eu/elmo-schemas/issues/44)

**Comment by ArnWassmann** [comment]
Hallo Herr Dietrich,

ok. Dann wäre es schön, wenn die inhaltliche Bedeutung des Ortes für die technische Nachricht klar definiert wird. Insbesondere im Zusammenhang mit xhs:hochschulsignatur, da hier abweichende Daten auftauchen können (Hochschulen mit Standorten) oder die Information redundant vorhanden sein wird.

- xbd:ort - "Ort der Ausstellung des Dokuments" <-- Das könnte der Standort des Servers sein?
- xhs:hochschulsignatur - "???" <-- Hier wird ein Standort der Hochschule angegeben (Hier ist auf Seite 25 der Spezifikation ein inhaltlicher copy+paste Fehler, vermutlich ist der Astat-Wert gemeint.)

Das Ganze hat aber keine Prio - Nice to have.

Vielen Dank und beste Grüße
Arn Waßmann
