### ISSUE TITLE
[Bug] Test messages failed to validate.

### ISSUE THREAD

**Issue by pascalhuerten** [OZG-TFBildung/XHochschule#2]
Creator: Pascal Hürten (TH Lübeck)
Type of the organisation: university
Description: Validation fails when xmllint is used to validate the test messages against the xsd schemas. The following example shows the result of validating testnachricht_nachweis.hochschulabschlusszeugnis.0003.xml against xhochschule-nachweis.xsd.

```
$ xmllint --schema xsd/xhochschule-nachweis.xsd xml/testnachricht_nachweis.hochschulabschlusszeugnis.0003.xml --noout
warning: failed to load external entity "https://www.w3.org/2009/01/xml.xsd"
http://xbildung.de/def/xbildung/0.4/xsd/xbildung-basisdatentypen.xsd:31: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'https://www.w3.org/2009/01/xml.xsd'. Skipping the import.
http://xbildung.de/def/xbildung/0.4/xsd/xbildung-basisdatentypen.xsd:38: element attribute: Schemas parser error : attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.
WXS schema xsd/xhochschule-nachweis.xsd failed to compile
```

Validating agaist xhochschule.xsd and trying to validate the other test messages show similar results.

**Comment by XHochschuleDE** [comment]
Hello Mr Hürten

thank you for your feedback. We appreciate that you shared the details of the bug you discovered. We will keep you updated on the current status of this issue and notify you as soon as we find a solution to this bug.

Oliver Budke

**Comment by XHochschuleDE** [comment]
@pascalhuerten We were able to reproduce your validation results with libxml version 20910. We will investigate the reason of the unsuccessful validation in our internal ticket [XHS-355](https://issues.init.de/browse/XHS-355).

**Comment by init-xhochschule** [comment]
Update: XHS test messages xsd schemas have changed extensively. Meanwhile validation of XHS documents has been demonstrated. For further information check out the current version 0.95 of XHS: https://xhochschule.de/def/xhochschule/0.95/
