### ISSUE TITLE
Exma-Besch: Herausforderung - Mapping von Schlüsselwerten: xhs:exmatrikulationsgrund - eigentlich irrelevant?

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#20]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Schlüsselwert
**Betroffenes Feld:** xhs:exmatrikulationsgrund

**Beschreibung:**
Die Werte aus Schlüsseltabellen des Statistischen Bundesamtes dienen der Bildung einer Statistik. Diese komprimieren bereits die Hochschulrealität sehr stark. Jede Hochschule kann sich eine Vielzahl von Exma-Gründen überlegen, wie bspw. "Das Essen in der Mensa schmeckt mir nicht", "Gleichberechtigung der Geschlechter ungenügend", "Todesfall", usw. Diese Vielzahl der Gründe, welche die HS benötigt, um selbst die eigene Qualität verbessern zu können, spiegeln sich in der amtlichen Statistik nicht wieder. Wäre beim Export aber auch egal, da es ja immer ein internes Mapping auf den offiziellen Wert gibt. Beim Import der Exma-Nachricht kann aber an der neuen Hochschule, jenseits des Statistikschlüssels, der eigentliche Grund nicht wieder hergestellt werden. Das ist aber auch nicht schlimm, denn der Grund für die Exma wird an der annehmenden Hochschule gar nicht erfasst. Er ist somit für die Nachricht vollständig irrelevant. Vielleicht gebe ich als Studierender als Grund bei der Exma einen Sachverhalt an, der sich kurze Zeit später ändert und diese Änderung dazuführt, dass ich doch an einer anderen Hochschule weiter studieren möchte.

Nach unserer Einschätzung ist der Exma-Grund nur für die abgebende Hochschule relevant (Meldung an die Statistik). Für die neue, annehmende Hochschule spielt der Exma-Grund keine Rolle und wird auch nicht erfasst und ist auch nicht für die Bildung einer weiteren Statistik relevant. Der Exma-Grund sollte daher, aus Gründen der Datensparsamkeit, nicht Teil der Nachricht sein. Wir werden ihn nicht im Rahmen eines Hochschulwechsels importieren.

P.S. Warum der Grund auf so manchem Papierbescheid steht, weiß ich auch nicht. Vermutlich aus der Kategorie: "War schon immer so". P.P.S. Vielleicht gibt es dafür aber auch tatsächlich Gründe? Sollte noch welche auftauchen, werde ich diese hier aufführen.

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihre Einschätzung. Wir werden noch einmal prüfen, ob der Exmatrikulationsgrund tatsächlich bei der Neuaufnahme eines Studiengangs an einer anderen Hochschule z.B. keine Rolle spielt, also an keine Stelle in diesem Prozess ausgewertet wird (AK Studienplatzwechsel). 

Falls sich darüber hinaus herausstellt, dass der Exmatrikulationsgrund auch bei anderen potenziellen Empfängern der ExmaBesch nicht verarbeitet wird (z.B. Jobcenter, Kindergeldstelle, Rentenversicherung, andere Sozialkassen) sollte er ganz aus dem Modell entfernt werden.

**Comment by XHochschuleDE** [comment]
Hallo Herr Wassmann,

wir haben bis jetzt nur einen Anwendungsfall für den Exmatrikulationsgrund gefunden, nämlich den Fall der Exmatrikulation aufgrund endgültig nicht bestandener Prüfung. Wie sich bei dem zweiten Arbeitskreis zum Studienplatzwechsel herausgestellt hat, ist die Abwesenheit dieser Angabe auf einer Exmatrikulationsbescheinigung keine hinreichend zuverlässige Entscheidungsgrundlage für Hochschulen. Da demnach kein Anwendungsfall für dieses Feld gegeben ist, wurde es in der Version 0.92 von XHochschule entfernt.

Danke nochmal für Ihren Beitrag

Robin Dietrich
