### ISSUE TITLE
Exma-Besch: xbd:identifikationsnummer technisch nicht auswertbar

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#21]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:**  Datentyp
**Betroffenes Feld:** xbd:identifikationsnummer

**Beschreibung:**
In HISinOne kann eine Vielzahl von (technischen) Personenidentifikatoren zu einer Person gehalten werden. Wir können somit eine Liste von **xbd:identifikationsnummer** füllen. Mit etwas Glück kann man einen davon zur sicheren Identifizierung einer Person beim Import nutzen (Sichere Authentifizierung mit ausreichendem Vertrauensniveau an der neuen Hochschule inkl. unabhängiger sowie glaubhafter Beibringung des gleichen Identifikators vorausgesetzt.). Diesen Abgleich können wir problemlos über die Werte machen. Gerne würden wir aber der Nachricht, wenn wir einen positiven Treffer haben, dann noch weiter vertrauen und alle aufgeführten (und noch unbekannten) Identifikatoren mitübernehmen also importieren. Dafür müssten wir aber technisch wissen um was für einen  Identifikator es sich inhaltlich handelt. Bisher sieht die Spezifikation nur einen Prosatext in Form einer Beschreibung vor. Hier sollte das Verfahren auch technischer eindeutig identifizierbar sein. Wir wünschen uns daher zusätzlich min. eine Schlüsseltabelle oder besser noch dedizierte Datentypen nach Vorbild von _xhs:matrikelnummer_.

**Comment by init-xhochschule** [comment]
Vielen Dank für diesen Hinweis. Mit Blick auf die Zukunft sind wir hier tatsächlich zu demselben Ergebnis gekommen. D.h. sobald eine (der verschiedenen dankbaren) Identifikationsnummer sich als nützlich / praxistauglich für den Datenaustausch im Rahmen von XHochschule erweist, sollte diese einen eigenen Datentyp bekommen, so wie das jetzt schon bei der xhs:matrikelnummer der Fall ist.
