### ISSUE TITLE
Exma-Besch: Internationaler Name der Hochschule xhs:ausstellendeHochschule

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#22]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Datentyp
**Betroffenes Feld:** xhs:ausstellendeHochschule -> xbd:name -> xbd:name

**Beschreibung:**
Wir wünschen uns, dass wir den Namen der Hochschulen auch mit dem internationalen Namen optional angeben können. Bezogen auf Ihr Beispiel wäre das zur _Universität des Saarlandes_ dann _Saarland University_ (EN) bzw. _Université de la Sarre_ (FR).

Warum steckt eigentlich xbd:name in xbd:name? Das ist sehr kompliziert nachzuvollziehen, denn der Typ _Hochschule_ ist eine Erweiterung des Basistyps _Bildungseinrichtung_ ist eine Erweiterung des Basistyps _Organisation_ ist eine _Behoerde_. Muss diese Komplexität wirklich sein, um so etwas triviales abzubilden?

In unserem Beispiel ist das Ergebnis lediglich:

<ns3:ausstellendeHochschule>
	<ns2:name>
		<ns2:name>Hochschule HIS</ns2:name>
	</ns2:name>
	<ns3:hochschulsignatur>
		<code>http://xhochschule.de/def/destatis/WS21/code/hochschulsignatur/9991</code>
	</ns3:hochschulsignatur>
</ns3:ausstellendeHochschule>

**Comment by init-xhochschule** [comment]
Besten Dank für die Hinweise. 

1) Wir werden prüfen, welchen Mehrwehrt die Ableitung: Organisation -> Bildungseinrichtung -> Hochschule für unser Datenmodell bietet und inwiefern sich diese Komplexität sinnvoll reduzieren lässt.

2) Verschiedensprachige Angaben des Hochschulnamens lassen sich modellseitig grundsätzlich leicht ermöglichen. 
Nachfrage dazu: Haben Sie bereits eine Idee, für welchen konkreten Zweck der digitale Datenaustausch eines solchen internationalen Hochschulnamens (zusätzlich zur Hochschulsignatur) im Rahmen von XHochschule nützlich sein könnte?

Viele Grüße
Martin Herzog

**Comment by ArnWassmann** [comment]
Hallo Herr Herzog,

will XHochschule ein internationaler Standard sein, wie man es auf der Webseite darstellt, dann müssen alle Felder mehrsprachig ausgelegt werden oder XHochschule ist ein Deutschlandstandard, dann wäre das wohl nicht nötig. Ich wünsche mir also eigentlich eine klare und eindeutige Positionierung von Ziel und Zweck sowie Geltungsbereich von XHEIE , um die Anforderungen klarer formulieren zu können. Welchen Wert würde denn bspw. die französische Hochschule von Amélie bei _ns3:hochschulsignatur_ eintragen?

Uns ist letztendlich nur aufgefallen, das wir dieses Feld füllen könnten und andere Felder zwischendurch auch mehrsprachig ausgelegt sind. Daher der Wunsch es optional angeben zu können. Hinweis: Mit HISinOne können Bescheide auch auf englisch ausgestellt werden, damit man diese als Studierende/r bspw. ins Ausland senden kann. Auch bei diesen Bescheiden könnten wir XHEIE-XML einbetten. Ist das auch so gedacht? Dann wäre der internationale Name der Hochschule auch schön.

Danke und Grüße
Arn Waßmann
