### ISSUE TITLE
Exma-Besch: Hinweis zur xhs:hochschulsignatur - Fehler in der Beschreibung

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#23]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Fehler
**Betroffenes Feld:** xhs:hochschulsignatur 

**Beschreibung:**
Beschreibungstext lautet: _Bezeichnung des erworbenen Zugangs zu einem weiterführenden Studium (ISCED Code 2011)._ (Abruf der Spezifikation am 28.02.22 in der Version 0.9)

Erwartung: _Wert der amtlichen Statistik zur eigenen Hochschule._

Hinweis: Viele Hochschulen haben mehr als einen Wert in der amtlichen Statistik, da jeder Standardort der Hochschule dort erfasst ist. Der Kommentar sollte dem zusätzlich Rechnung tragen.

**Comment by init-xhochschule** [comment]
Vielen Dank für diesen Hinweis!
Wir werden den Beschreibungstext für die Hochschulsignatur in der kommenden Version entsprechend korrigieren.
