### ISSUE TITLE
Exma-Besch: Hinweis zu xhs:studienfach

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#24]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Allgemein
**Betroffenes Feld:** xhs:studienfach

**Beschreibung:**
Allgemeiner Hinweis: Auf einer Exma-Bescheinigung werden nur die Studienfächer aufgeführt, die im Semester der Exma beendet werden. Studienfächer die bereits vor diesem Semester abgeschlossen wurden, finden hier keine Berücksichtigung. Es kann also nie von einer vollständigen Liste aller jemals an dieser Hochschule studierten Fächer ausgegangen werden.

**Comment by init-xhochschule** [comment]
Vielen Dank für den Hinweis!
Hier scheint es allerdings unterschiedliche Varianten in der Praxis zu geben. Wir haben im Zuge der Modellierung auch Exma-Bescheinigungen gesehen, die den Studienverlauf auch vorheriger Semester abgebildet haben. Ggf. lässt sich auch hier im Rahmen des AK Studienplatzwechsel Klarheit schaffen, wann man welche Variante braucht und wofür.

**Comment by init-xhochschule** [comment]
Im Arbeitskreis Studienplatzwechsel vom 23.03.2022 wurde festgestellt, dass die Angabe des Studienverlaufs auf der Exmatrikulationsbescheinigung sinnvoll ist zur Berechnung von Studiengebühren. Einige Hochschule benutzen genau diese Informationen direkt von der Exmatrikulationsbescheinigung, weshalb diese Angabe auch weiterhin in der aktuellen Spezifikation von XHochschule verfügbar ist.
