### ISSUE TITLE
Exma-Besch: Schlüsseltabelle xhs:angestrebterAbschluss in der Praxis untauglich

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#25]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Datentyp
**Betroffenes Feld:** xhs:angestrebterAbschluss

**Beschreibung:**
Die Werte in der Schlüsseltabelle http://xbildung.de/def/xbildung/0.9/code/ArtDesAbschlusses existieren so an keiner Hochschule. Sie sind Umgangssprache. HISinOne liefert in seiner internen Schlüsseltabelle über 150 verschiedene Studienabschlüsse aus und in der Realität sind es sogar noch mehr. Die Hochschulen sind hier sehr kreativ und frei. Die amtliche Statistik (Landesstatistik und Bundesstatistik) kennt kapp 100 Abschlüsse. Die Abschlüsse der Hochschule werden dann auf den nächststehenden offiziellen Statistikwert gemappt. 

Auch hier würde beim Mapping auf Ihre Schlüssel die nötigen Inhalte verloren gehen und stünden beim Import nicht zur Verfügung. Leider ist dieser Wert relevant für die amtl. Statistik und muss bei der Imma im Rahmen des Hochschulwechsels (genau) erfasst werden. So wie es hier abgebildet ist muss folglich der Studierende manuell eingreifen und eine Auswahl treffen. Man könnt mit Ihrem Wert bestenfalls die Auswahlliste noch etwas filtern.

Aber selbst in Ihrer sehr stark vereinfachten Darstellung des Abschlusses fehlen Werte, wie bspw. _Magister_. 

Leider habe ich auch gerade keine gute Idee wie man diese Komplexität interoperabel gestalten könnte.

**Comment by init-xhochschule** [comment]
Vielen Dank für den Hinweis! 
Wir werden für die nächste Version von XHochschule und XBildung prüfen, ob, bzw. für welchen Anwendungsfall die Codeliste  http://xbildung.de/def/xbildung/0.9/code/ArtDesAbschlusses nutzbringend ist. Weitere Diskussion und Aufschluss dazu erhoffen wir uns ebenfalls vom AK Studienplatzwechsel (erster Termin am 23.3.).

**Comment by init-xhochschule** [comment]
Update: In den bisherigen Arbeitskreisen zum Thema Studienplatzwechsel konnte noch nicht geklärt werden, welche Statistik-Werte von DESTATIS tatsächlich auch sinnvoll für den Datenaustausch einsetzbar sind für Anwendungsfälle im Rahmen von XHochschule (also jenseits von Statistikmeldungen der einzelnen Hochschulen). Wir prüfen diese Fragestellung daher weiter mit Blick auf das nächste Release von XHochschule.

**Comment by init-xhochschule** [comment]
Update: Das Datenfeld angestrebterAbschluss ist inzwischen vom Datentyp String, siehe XHS Version 0.95: https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf 

Viele Grüße
Ihr Team von XHochschule
