### ISSUE TITLE
Exma-Besch: Die Sache mit den Schlüsselwerten der amtlichen Statistik

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#26]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Allgemein
**Betroffenes Feld:** Alle Schlüsselwerte von DESTATIS

**Beschreibung:**
Die Wertelisten der amtlichen Statistik dienen dem einheitlichen Erfassen einer Statistik. Jede Hochschule hat i.d.R. eigene (ergänzende) Werte, die auf einen offiziellen Wert verweisen.

Beispiel Studienabschluss:
_Magister Artium_ (so nennt es die Hochschule) wird abgebildet auf den Landesschlüssel 02 und auf den Bundesschlüssel 02. Das lässt sich mit Ihren Werten aktuell nicht darstellen. In der Bundesstatistik heißt der Abschluss nur _Magister_. Kommt also beim Import ein 02, dann kann das nicht sicher auf _Magister_ oder _Magister Artium_ zurückgeführt werden. Das gilt für alle Schlüsseltabellen der Statistik!

Die Kernfrage ist also, was will man mit dem elektronischen Exma-Bescheid eigentlich erreichen?

Manche Statistikwerte werden im Rahmen eines Hochschulwechsels nur von der abgebenden Hochschule gemeldet. Diese Werte müssen also nicht über eine XHEIE-Nachricht transportiert werden. Manche Werte werden von der annehmenden Hochschule gemeldet und mache von beiden Hochschulen.

a)
Will man also erreichen, dass ein Studierender im Rahmen des Hochschulwechsels möglichst keine Eingaben mehr machen muss, dann müssen die Werte, welche die abgebende Hochschule liefert und von der annehmenden Hochschule gemeldet werden, enthalten sein.

b)
Will man erreichen, dass lediglich der Studierendenstatus sauber übermittelt wird, dann kann man auf diese Werte verzichten.

Ist der Anspruch a, dann muss auf die Landesämter Rücksicht genommen werden, da die allermeisten Hochschulen gemäß ihren Landesämtern Daten erheben und melden. Die Bundesschlüssel sind da im Detail nicht immer ausreichend.

Wovon auf jeden Fall Abstand genommen werde sollte ist der Versuch die Statistikwerte für die Schaffung von Interoperabilität heranzuziehen. Das scheitert auf der Importseite, da mit den Werten oft keine eindeutige Zuordnung auf die hochschulindividuellen Werte möglich ist. Es ist beim Import eine m:1 Beziehung!

Bestenfalls kann man mit den Werten etwas Filtern oder sie zur Anzeige bringen, quasi neben einer Auswahlliste, aber ohne manuellen Eingriff wird es so nicht gehen.

Was ist also der Plan? Was will man mit einer elektronischen Exma-Bescheinigung genau erreichen?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Kommentar. Das ist genau der richtige Ansatz und die konkrete Fragestellung, der wir uns im Rahmen der Datenmodellierung immer wieder stellen: "Die Kernfrage ist also, was will man mit dem elektronischen Exma-Bescheid eigentlich erreichen?" 

Durch diese Frage wird auch schnell klar, dass die Exmatrikulationsbescheinigung aber nur ein Puzzleteil ist und wir daher gemeinsam im Arbeitskreis Studienplatzwechsel (am 23.3.) die übergeordnete Frage untersuchen wollen: "Welche Schritte im Rahmen eines Studienplatzwechsels lassen sich durch den digitalen Datenaustausch sinnvoll erleichtern, z.B. durch (Teil-)Automatisierung. 

Dabei wird es u.A. auch auch um den Austausch von Statistikwerten gehen und wir können Ihren Input dabei sicher gut nutzen. Schließlich wird es danach auch um die Frage, welcher Wert steht nun am Ende auf welcher Bescheinigung / auf welchen Bescheinigungen (hier gibt es an den HS / in den BL ziemlich viel Heterogenität, die wir zumindest teilweise schon kennengelernt haben). 

Beste Grüße
Martin Herzog

**Comment by init-xhochschule** [comment]
Update: In den bisherigen Arbeitskreisen zum Thema Studienplatzwechsel konnte noch nicht geklärt werden, welche Statistik-Werte von DESTATIS tatsächlich auch sinnvoll für den Datenaustausch einsetzbar sind für Anwendungsfälle im Rahmen von XHochschule (also jenseits von Statistikmeldungen der einzelnen Hochschulen). Wir prüfen diese Fragestellung daher weiter mit Blick auf das nächste Release von XHochschule.

**Comment by init-xhochschule** [comment]
Update: Inzwischen gab es für die Version XHS 0.95 die folgenden Änderungen bzgl. der Destatis-Codelisten (siehe Versionshistorie der aktuellen Spezifikation) https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf 

III.E.1.2.1. Streichung der Destatis-Codelisten "Studienbereich", "Fächerschlüssel", "Art der Hochschule"
und "Art des Hochschulabschlusses"

Beide Codelisten haben sich in mehrfacher Hinsicht als nicht sinnvoll zur weiteren Verwendung im
Datenmodell erwiesen. Um Probleme bei der Konsistenz wie der Persistenz der Identifikatoren zu vermeiden
und wegen des geringen Mehrwerts für das Datenmodell werden diese ausgebaut.

III.E.1.2.2. Umstellung von Destatis-Codelisten auf XÖV-Codelisten-Nutzungstyp 3

Verbleibende Destatis-Codelisten "Hochschulsignatur" und "Beurlaubungsgrund" werden als Typ3-
Codelisten ("Benannte Codeliste") eingebunden, damit ihre Werte über verschiedene Versionen hinweg
gültig und referenzierbar bleiben, siehe XÖV-Codelisten-Handbuch der KoSIT, S. 11.

Viele Grüße
Ihr Team von XHochschule
