### ISSUE TITLE
Exma-Besch: Bezeichnung Semester nicht immer treffend - xhs:fachsemester

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#27]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Bedeutung unklar
**Betroffenes Feld:** xhs:fachsemester

**Beschreibung:**
Siehe dazu bitte auch https://github.com/OZG-TFBildung/XHochschule/issues/13

Nicht jede Hochschule zählt in Semestern. Mancher Orts haben wir Trimester oder Quartale. Dies sollte sich mindestens im Beschreibungstext der Spezifikation wieder finden. Dort steht immer nur Semester.

Hinweis: 
Trimester werden nicht 1, 2 oder 3 durchgezählt. Siehe dazu bspw. https://de.wikipedia.org/wiki/Trimester_(Studium)
Siehe dazu auch den Beschreibungstext periodenangabe -> periode in der Spezifikation.

**Comment by init-xhochschule** [comment]
Vielen Dank für den Hinweis! 
Den Beschreibungstext von xhs:fachsemester werden wir in der Spezifikation entsprechend anpassen. Wie aktuell schon bei den Feldern xhs:hochschulsemester und xhs:urlaubssmester erläutert, wird es auch hier den Hinweis geben, dass andere Einteilungen, z.B. Trimester entsprechend umgerechnet auf Semester angegeben werden können (daher Datentyp double). Gleiches gilt für die Periodenangabe.

Grund dafür ist, dass es (nach den bisherigen Erkenntnissen) noch keinen erkennbaren Fall gibt, in dem eine andere Periodeneinteilung als Semester für den Datenaustausch relevant oder sinnvoll umsetzbar erscheint. Das liegt wiederum daran, dass die Länge von z.B. Trimestern an dt. Hochschulen stark variiert, zw. 3 und 4 Monaten. Es stellt sich außerdem die Frage, inwieweit, bzw. wofür diese Angabe (ohne ein genaues Start + Enddatum) überhaupt nützlich wäre, z.B. für die Berechnung von Studiengebühren innerhalb des Anwendungsfalls Studienplatzwechsel. Dieser Frage wollen wir daher im Arbeitskreis Studienplatzwechsel noch ein mal nachgehen.

**Comment by init-xhochschule** [comment]
Im Arbeitskreis Studienplatzwechsel am 23.03.2022 wurde festgestellt, dass keinen erkennbaren Anwendungsfall oder Bedarf für den Datenaustausch von Studienperioden jenseits von Semesterangaben gibt.
