### ISSUE TITLE
Exma-Besch: unseco vs. unesco

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#28]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Fehler
**Betroffenes Feld:** xhs:schluesselISCED2011

**Beschreibung:**
urn:xbildung-de:**unseco**:codeliste:isced2011

Basiert auf: https://xbildung.de/def/xbildung/0.9/spec/spezifikation_0.9.pdf#XBildung.Baukasten.Codes.Code.ISCED2011

**Comment by init-xhochschule** [comment]
Dieser Fehler wurde in der Version 0.91 behoben:
https://xhochschule.de/def/xhochschule/0.91/spec/spezifikation_0.91.pdf

Vielen Dank für den Hinweis.
