### ISSUE TITLE
Exma-Besch: Beispieldateien der HIS eG

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#29]
**Autor:** Arn Waßmann
**Art der Organisation:** CAMS-Hersteller
**Name der Organisation:** HIS eG

**Kategorie(n) der Rückmeldung:** Allgemein 

**Beschreibung:**
Hallo,

wir möchten gerne unsere von HISinOne generierten Beispieldateien teilen. Wie soll dies erfolgen. Ich habe habe keine Berechtigung diese im Repo zu pushen.

Danke und Grüße
Arn Waßmann

**Comment by init-xhochschule** [comment]
Hallo Herr Waßmann,

bitte tun Sie Ihre generierten Beispieldateien in eine ZIP-Datei und fügen diese dann per Drag&Drop zu einem neuen Issue "Beispieldateien der HIS eG" hinzu. 

Besten Dank und viele Grüße
Martin Herzog

**Comment by ArnWassmann** [comment]
Ok, hier die Dateien.

[xheie-exmabesch_pilotierung.zip](https://github.com/OZG-TFBildung/XHochschule/files/8265004/xheie-exmabesch_pilotierung.zip)

**Comment by XHochschuleDE** [comment]
Vielen Dank für die Dateien. 
Wir werden die Dateien in Kürze untersuchen und validieren und Sie über die Ergebnisse auf dem Laufenden halten.

Robin Dietrich
