### ISSUE TITLE
Verknüpfung von XHochschule mit anderen Plattformen/Datenbanken

### ISSUE THREAD

**Issue by Akademie66111** [OZG-TFBildung/XHochschule#3]
Autor: Raimund Gründler
Art der Organisation: Private Berufsakademie
Beschreibung: 
XHochschule wird es erforderlich machen, für jeden Studierenden eine Datensatz anzulegen. Es wäre sicherlich sinnvoll, die Struktur so anzulegen, dass dieser Datensatz auch gleichzeitig die Grundlage für weitere notwendige Datenverarbeitungen sein könnte:
- Statistische Jahresmeldungen Hochschulstatistik/Studierendenstatistik
- Anlage der Studierenden für Mailzugänge, Officepakete, Bibliotheksnutzung etc.

**Comment by ArnWassmann** [comment]
Guten Tag Herr Gründler,

auch wir hatten in der Vergangenheit diese Frage gestellt, ob mit XHochschule auch die Identität übertragen werden sollte.

Meiner persönlichen Meinung nach sollte sich XHochschule auf den Austausch der fachlichen Daten konzentrieren, also den Imma-Status oder die Noten. Die Übertragung der Identität muss über ein anderes Verfahren, mit einem definierten technischen Protokoll, erfolgen. Möglicherweise helfen hier die Nutzerkonten, bspw. vom Bund. Ich hätte am liebsten zu einer Person nur einen eindeutigen technischen Identifier und sonst keine Personenstammdaten im XML.

Viele Grüße
Arn Waßmann

HIS Hochschul-Informations-System eG

**Comment by XHochschuleDE** [comment]
Guten Tag Herr Gründler,

wir bedanken uns bei Ihnen für Ihre Rückmeldung. Wir werden das von Ihnen vorgebrachte Anliegen diskutieren und Sie in Zukunft an dieser Stelle über den aktuellen Status und weitere Erkenntnisse informieren.

Viele Grüße,
Oliver Budke

**Comment by XHochschuleDE** [comment]
@ArnWassmann Viele Antworten auf die von Ihnen aufgeworfenen Fragen werden Sie im Pflegekonzept und Implementierungshandbuch finden. In diesen beiden Dokumenten, die noch zu erarbeiten / veröffentlichen sind, wird es Vorgaben zu Aufwärts- und Abwärtskompatibilitäten von XHochschule geben.

Wir sehen es als Aufgabe von XHochschule an, dem Releasemanagement unterliegende Versionssprünge zu gewährleisten. Dadurch ist eine Vereinfachung für Implementierende zu erwarten, da eingebundene Schemata gekapselt und nicht mehr einzeln implementiert werden müssen. Bereits jetzt lässt sich sagen, dass Abwärtskompatibilität in kleinen Versionssprüngen (d.h. Minor-Releases) gewährleistet sein wird.

XHochschule arbeitet Änderungen stets so ein, dass wenige Releasewechsel entstehen. Tatsächlich denken wir, dass aufgrund sich ändernder Registerlandschaften, zunehmender Fachverfahrensvernetzung und des Datenaustauschs mit Europa und Sozialversicherungsträgern zweimal im Jahr Anpassungen an den Modellen erforderlich werden. Wir haben andere, einschlägige Vorhaben auf dem Radar und bringen uns im Interesse des deutschen Bildungswesen (Hochschulen sowie Ministerien) dort ein (EDCI https://github.com/european-commission-europass/Europass-Learning-Model, SDG https://github.com/SEMICeu/SDG-sandbox, XInneres https://www1.osci.de/meldewesen/xmeld-2827). Bedenken Sie bitte, dass durch XÖV Änderungen an Codelisten auch unterjährig stattfinden werden.
