### ISSUE TITLE
Übertragung einer XHEIE-Nachricht über die Nutzenden an eine dritte Stelle

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#35]
Autor: Arn Waßmann
Art der Organisation: CAMS-Hersteller
Beschreibung: 

Ich beziehe mich auf das Treffen 'AG Schnittstellen / "runder Tisch der CamS"' und Ihre E-Mail vom 15.03. an die CaMS-Hersteller. Da ich auf meine E-Mail vom 21.03. bisher keine Reaktion erhalten habe, möchte ich meine Anmerkungen auch hier dokumentieren.

Laut Protokoll haben haben die CaMS-Hersteller beschlossen, dass XHEIE in PDF-Dokumente eingebettet werden sollen. Dies ist weder die beste Lösung noch die schönste. Sie ist, aus meiner Sicht, die einzige brauchbare Lösung, wenn es dabei bleibt, dass im Rahmen von XHEIE kein technisches Protokoll vorgeben wird und wir den Studierenden und Bewerber/innen kein XML direkt zum Download anbieten wollen.

Dennoch gibt es Rahmenbedingungen, die unbedingt von XHEIE vorgeben werden und beachtet werden müssen, damit das Ganze technisch interoperabel funktioniert. Das darf sich nicht jeder Hesteller selbst ausdenken, sonst geht die Interoperabilität verloren.

Daher bitte ich Sie um die folgenden Dinge:
* Erstellung einer technischen Beschreibung / Vorgabe, wie die Einbettung in eine PDF-Datei genau erfolgen soll (PDF-Typ, Signatur, Umgang mit abweichenden Inhalten zur XHEIE-Nachricht, etc.)
* Abstimmung und Harmonisierung mit anderen Gesetzen und Verordnungen:
** BITV (wie werden die Inhalte zugänglich?)
** Archivrecht (ich empfehle eine Kontaktaufnahme mit _nestor_: https://www.langzeitarchivierung.de/)
** usw.

Vielen Dank und beste Grüße
Arn Waßmann

**Comment by init-xhochschule** [comment]
Vielen Dank für diesen Hinweis. Die Klärung der technischen Vorgaben für die von Ihnen beschriebene Datenübertragung (XML-Datei eingebettet in ein PDF-Dokument) ist nicht Aufgabe von XHochschule. Inzwischen hat sich dafür bereits der "Runde Tisch" der CaMS-Hersteller gebildet, um sich auch der Frage zu widmen, welche Parameter hier am sinnvollsten sind.

Viele Grüße
Martin Herzog
