### ISSUE TITLE
DIN SPEC 

### ISSUE THREAD

**Issue by mrhuber71** [OZG-TFBildung/XHochschule#37]
Autor: Mathias R. Huber
Art der Organisation: Technische Universität Graz - CAMPUSonline
Beschreibung: DIN 91379:2022-08 ersetzt DIN SPEC 91379

Seit August 2022 gibt es die Norm DIN 91379:2022-08. Mit dem Beschluss 2022/51 vom IT-Planungsrat soll die DIN Norm an Stelle der DIN SPEC verwendet werden.

Siehe: [IT-Planungsrat | 10.11.2022 | 39. Sitzung | Beschluss 2022/51](https://www.it-planungsrat.de/beschluss/beschluss-2022-51)

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis, in der kommenden Version von XBildung und XHochschule werden wir diesen Datentypen entsprechend anpassen - dies geschieht durch das Update auf XÖV 3.0.
Viele Grüße
Ihr Team von XHochschule
