### ISSUE TITLE
Issue HAZ: Unterschiedliche Kodierung von <xbd:note>

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#38]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

In den Beispieldateien sind die deutschen Noten mal mit Dezimalpunkt, mal mit Komma geschrieben. Noten sind vom Typ String. “2.0” und “2,0” sind unterschiedliche Zeichenketten. Im Standard sollte eindeutig festgelegt werden, wie die typischen deutschen Noten kodiert werden. (T06_HAZ_max_positiv.xml ist mit Punkt; T03_HAZ_min_positiv.xml ist mit Komma).

**Comment by init-xhochschule** [comment]
Wir haben für die Version XHS 0.95 eine Schematronregel erstellt, die die Zeichen im Feld xbd:Benotung auf das Schema "Zahl" - "Komma" - Zahl" begrenzt. 
Viele Grüße
Ihr Team von XHochschule
