### ISSUE TITLE
Issue HAZ: angestrebterAbschluss pro Fach bei Mehr-Fach-Studiengang fragwürdig

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#39]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

In xhs:hochschulabschlusszeugnis können (richtigerweise) mehre Studienfächer (studienfach 1..n) angegeben werden. In jedem Studienfach ist angestrebterAbschluss ein Pflichtfeld (1:1). Das finden wir merkwürdig. Sollte nicht angestrebterAbschluss ein Pflicht- oder sogar nur Wahlfeld des Studiums sein? Welches Konzept liegt dem zugrunde, für jedes Fach eines Mehr-Fach-Studiengangs einen angestrebten Abschluss anzugeben?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Wir prüfen das und beziehen diese Überlegung in die Weiterentwicklung von XHS mit ein.
Viele Grüße
Ihr Team von XHochschule

**Comment by XHochschuleDE** [comment]
Wir haben im Rahmen der Version 0.95 Leistungsdaten in das Datenmodell integriert. Im Hochschulabschlusszeugnis gibt es nun das optionale Datenfeld "Abschluss" auf oberster Ebene und für die Studienfächer die Möglichkeit, diese als "Leistungen" zu verschachteln ("angestrebter Abschluss" ist hier ebenfalls optional). Damit sollte dieses Problem nach unserem Verständnis gelöst sein. 

Viele Grüße
Ihr Team von XHochschule
