### ISSUE TITLE
Stabilität der XSD für den Export möglich?

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#4]
Autor: Arn Waßmann
Art der Organisation: HIS Hochschul-Informations-System eG
Beschreibung: 

Guten Tag liebe Kolleginnen und Kollegen,

wir haben in HISinOne prototypisch und auf die schnelle aus der XSD (http://xhochschule.de/def/xhochschule/0.4/xsd/xhochschule-nachweis.xsd) mittels JAXB ein Java-Objektmodell erzeugt. Die Java-Klassen sind notwendig, damit wir einen Builder programmieren können, der die fachlichen Daten aus unserer Datenbank in das XHochschule-XML-Format transformiert. Unser Beispiel war die Studienbescheinigung nach §9 für BAföG. 

Die Erzeugung hat sich relativ aufwändig gestaltet und war aufgrund der zahlreichen externen Abhängigkeiten nicht mit allen XHochschule-XSD's möglich.

JAXB hat 359 Dateien in 62 Ordnern erzeugt. Das ist für den Transport einer handvoll Daten Wahnsinn! Jede Änderung im XSD kann sich auch auf das Objektmodell auswirken und führt Programmierarbeiten nach sich, die immer erst in einem zukünftigen Release von HISinOne bei den Hochschulen ankommen. Eine Hochschule kann nicht zu jeder Zeit einen Release-Wechsel durchführen. Eigentlich gibt es dazu nur zwei Gelegenheiten im Jahr. Wir veröffentlichen auch nur zwei Releases pro Jahr und nicht jede Hochschule nimmt jedes Release mit. So kommt es in der Praxis vor, dass erst 1,5 Jahre nach dem wir das XSD implementiert haben dieses an der Hochschule ankommt und durch diese verwendet werden kann.

In Ähnlichen Fällen garantiert die Gegengenstelle die Stabilität der Schnittstelle. So können bspw. Jahre lang auch ältere Schnittstellenspezifikationen der Stiftung (DoSV) verwendet wird. Die Version 2 läuft dort z.B. im Herbst diesen Jahres aus, die Version 3 im Herbst des nächsten Jahres und die aktuelle Version 4 läuft noch für unbestimmte Zeit. **Ich bitte daher schon jetzt darum diesen Umstand mitzudenken und auch zu definieren.**

Weitere Erkenntnisse, Fragen und Hinweise aus unserem Test:
- Was gibt es für Planungen bzgl. der Stabilität und der Versionierung der XHochschule-Spezifikation für die exportierende Stelle?
- Es ist aus unserer Sicht unpraktikabel für wenige Nutzdaten einen gigantischen Overhead im Datenmodell zu erzeugen. Es sollten nicht dutzende externe XSD's eingebunden werden.
- Es muss klar definiert und beschrieben werden, wie und aus welcher XSD für welchen Anwendungsfall ein Objektmodell erzeugt werden soll.
- Das Verhältnis von Nutzdaten zu Strukturdaten muss optimiert werden. Bei unserem Versuch lagen wir bei etwa 97% Overhead.
- Zirkulare Imports der verschiedenen eingebundenen Schemata müssen vermieden werden. Man muss ganz schön tricksen um das zum Laufen zu bekommen.
- Welche Vorstellungen / Ideen gibt es auf Ihrer Seite zum praktischen Einsatz für das Szenario Export?

Für die Praxis ist die Stabilität der Schnittstelle sehr wichtig.

Viele Grüße
Arn Waßmann

**Comment by XHochschuleDE** [comment]
Guten Tag Herr Waßmann,

wir bedanken uns bei Ihnen für Ihre Rückmeldung. 

Könnten Sie uns die (Error)Logs der JAXB-Generierung bitte per Mail an info@xhochschule.de zukommen lassen? Vielen Dank. Bezüglich der weiteren Punkte aus Ihrer Rückmeldung werden wir uns zeitnah bei Ihnen melden.

Viele Grüße,
Oliver Budke

**Comment by init-xhochschule** [comment]
Guten Tag. Durch die verfügbare Version 0.92 von XHochschule und die begonnene Pilotierung sind die aufgeführten Punkte inzwischen adressiert und das Ticket daher geschlossen.  Falls es von Ihrer Seite dennoch Klärungsbedarf zu einem konkreten Aspekt gibt, bitten wir um Erstellung eines neuen Issues genau dazu.  Vielen Dank für Ihre Mitwirkung!
