### ISSUE TITLE
Issue HAZ: Codelisten für xbd:Code.Bewertungsschema unvollständig

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#40]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

Die bisherigen Codelisten für xbd:Code.Bewertungsschema sind unvollständig. Sogar die typischen Beurteilungsskalen wie Drittelnoten, Zehntelnoten, Jura-Punkte usw. fehlen. Werden diese noch ergänzt? Das würde dann ggf. auch die Notation klären (“2.0” vs. “2,0). Im xbd- oder im xhs-Namespace?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Die Codeliste wird mit dem Release von XBildung 0.94 entsprechend erweitert. 
Viele Grüße
Ihr Team von XHochschule
