### ISSUE TITLE
Issue HAZ: Formatierung Titel der Abschlussarbeit

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#41]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

Der Titel der Abschlussarbeit wird bei uns teilweise formatiert (bold, italic, Mathematische Formeln usw.) gespeichert. Was ist im Standard vorgesehen?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Im Standard ist derzeit nicht vorgesehen, andere Zeichensätze als String.Latin.Plus für den Titel zu verwenden. Für Titel-Angaben, die damit nicht abbildbar sind, sollte von Anwenderseite eine XHS-konforme Transkription bereitgestellt werden.
Viele Grüße
Ihr Team von XHochschule
