### ISSUE TITLE
Issue HAZ: xbd:wortbezeichnung enthält Titel der Abschlussarbeit

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#42]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

In der positiv-Testdatei für das Zeugnis (T06_HAZ_max_positiv.xml) ist in xbd:wortbezeichnung der Note noch mal der Titel der Abschlussarbeit in Englisch drin. War das nur ein Versehen? 

xbd:titelDerArbeit mit anderem xml:lang wäre korrekt, richtig?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Wir werden diesen Fehler korrigieren. 
Viele Grüße
Ihr Team von XHochschule

**Comment by init-xhochschule** [comment]
Update: Der Fehler wurde inzwischen behoben, siehe aktuelle Beispielinstanz des Hochschulabschlusszeugnisses: https://xhochschule.de/def/xhochschule/0.95/xml/Hochschulabschlusszeugnis.xml
Viele Grüße
Ihr Team von XHochschule
