### ISSUE TITLE
Issue HAZ: alte Codelisten derzeit nicht verfügbar

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#43]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

Die Schlüssel der DESTATIS werden zwar als Codelisten pro Semester ausgeliefert, aber es scheint, dass alte Codelisten derzeit nicht mehr verfügbar sind. Wir planen, die Daten im Hochschulabschlusszeugnis mit den Schlüsseln für das Abschlusssemester zu kodieren. Diese müssten dann aber auch verfügbar bleiben. Was ist hier der Plan?

**Comment by KTowet** [comment]
Die Verfügbarkeit nicht mehr aktiver Schlüssel ist auf jeden Fall in vielen Bereichen wichtig. Ein weiterer Anwendungsfall sind Bewerbern mit einem Vorstudium an einer Hochschule, die es nicht mehr gibt, bzw. deren Hochschulsignatur sich geändert hat (z.B. früher: 1630 TU München, jetzt 1631 TU München in München, 1632 TU München in Weihenstephan....)

**Comment by mrhuber71** [comment]
Siehe auch #50 
Code-Listen sollten meiner Meinung nach nicht im Schema als Enumerationen definiert sein. Gültige Werte sollten beispielsweise von einer anderen Quelle importiert werden können.

**Comment by init-xhochschule** [comment]
Vielen Dank für diesen Hinweis. Das ist ein wichtiges Thema, das wir auch gerade mit anderen Vorhaben diskutieren und wir beziehen es in die Weiterentwicklung von XHochschule ein.
Viele Grüße
Ihr Team von XHochschule

**Comment by init-xhochschule** [comment]
Update: Die Codeliste Hochschulsignatur wird ab dem nächsten Release zur Typ-3 Codeliste. Auf diese Weise wird den verschiedenen Versionen der Hochschulsignaturliste Rechnung getragen. 

Hintergrund: Es befinden sich beispielsweise ältere Versionen der Codeliste in Anwendung. Daher gilt: Es sollte immer der Codelistenwert aus derjenigen Version verwendet werden, mit der ein Dokument ursprünglich erstellt wurde. Vorherige Versionen der Schlüsselliste bleiben für den Zeitraum, auf den sie sich beziehen, gültig. Zusammen mit dem Schlüssel muss die verwendete Version des Schlüsselverzeichnisses im XML-Element in dem Attribut listVersionID angegeben werden. Für Schlüssel aus dem Schlüsselverzeichnis "WS 2022/2023 und SS 2023" würde die Version wie folgt angegeben: listVersionID="WS_2022". Bitte geben Sie Ihren Bezugsort für die Codeliste, die Sie verwenden unter dem Attribut "listURI" an.

Viele Grüße
Ihr Team von XHochschule
