### ISSUE TITLE
Issue HAZ: Überschreibung Bundes- durch Landes-Schlüssel nicht berücksichtigt

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#44]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

Die DESTATIS-Schlüssel sind speziell, da Bundes-Schlüssel durch Landes-Schlüssel “überschrieben” werden können. Dies ist bisher nicht berücksichtigt. Vielleicht wird das ja auch abgeschafft?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Was genau meinen Sie mit "überschrieben"? An welcher Stelle genau ergibt sich hier ein Problem? Könnten Sie das evt. näher erläutern?
Viele Grüße
Ihr Team von XHochschule

**Comment by init-xhochschule** [comment]
Update: Inzwischen gab es für die Version XHS 0.95 folgende Änderung bzgl. der Destatis-Codelisten (siehe Versionshistorie der aktuellen Spezifikation) https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf

III.E.1.2.2. Umstellung von Destatis-Codelisten auf XÖV-Codelisten-Nutzungstyp 3

Verbleibende Destatis-Codelisten "Hochschulsignatur" und "Beurlaubungsgrund" werden als Typ3-
Codelisten ("Benannte Codeliste") eingebunden, damit ihre Werte über verschiedene Versionen hinweg
gültig und referenzierbar bleiben, siehe XÖV-Codelisten-Handbuch der KoSIT, S. 11.

Viele Grüße
Ihr Team von XHochschule
