### ISSUE TITLE
Issue HAZ: Sub-Namespaces nicht genau definiert

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#45]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

Was die Sub-Namespaces der DESTATIS-Schlüssel angeht, sind in der Regel “WS” und “SS” (insbesondere letzteres wegen der deutschen Geschichte) als Abkürzung unerwünscht. Außerdem: Wenn Semester als Sub-Namespaces beibehalten werden, weil die Erstellung der Hochschulstatistik semesterweise erfolgt, sollte definiert werden, was WS22 bedeutet. (In der Regel ist es das Semester, das im Herbst 2022 beginnt und nicht das, das im Winter 2023 endet!)

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Wir orientieren uns hier an der von DESTATIS verwendeten Terminologie, also z.B. "WS22/23". Wir überprüfen, in der Weiterentwicklung von XHochschule für mehr Klarheit dementsprechend die Bezeichnung zu ändern, z.B. zu "WS_22_23". Da die Statistik von DESTATIS immer nur für das Wintersemester herausgegeben wird, ergeben sich auch keinerlei sprachliche Probleme für das Sommersemester. 
Viele Grüße
Ihr Team von XHochschule

**Comment by mrhuber71** [comment]
Eine alternative zu den hier genannten Schlüsseln "WS22" bzw. "SS22" etc. welche bereits bei anderen Universitäten und Hochschulen in Verwendung sind: W2022 bzw. S2022. Obwohl das ziemlich unwahrscheinlich sein wird, mit der gesamten Jahreszahl wird kein "Jahrhundertproblem" auftreten können.

**Comment by init-xhochschule** [comment]
Update: Inzwischen gab es für die Version XHS 0.95 die folgende Änderung bzgl. der Destatis-Codelisten (siehe Versionshistorie der aktuellen Spezifikation) https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf

III.E.1.2.2. Umstellung von Destatis-Codelisten auf XÖV-Codelisten-Nutzungstyp 3

Verbleibende Destatis-Codelisten "Hochschulsignatur" und "Beurlaubungsgrund" werden als Typ3-
Codelisten ("Benannte Codeliste") eingebunden, damit ihre Werte über verschiedene Versionen hinweg
gültig und referenzierbar bleiben, siehe XÖV-Codelisten-Handbuch der KoSIT, S. 11.

Viele Grüße
Ihr Team von XHochschule
