### ISSUE TITLE
Issue HAZ: Umgang mit der DokumentID unklar

### ISSUE THREAD

**Issue by jbuelau** [OZG-TFBildung/XHochschule#46]
**Autor:** Jessica Bülau
**Art der Organisation:** CaMS-Hersteller
**Name des CaMS-Herstellers:** S4Campus AG

Der Umgang mit der DokumentID im Hochschulabschlusszeugnis, DS und ToR ist unklar. 

Vorschlag: Man könnte sich darauf einigen, dass eine GUID erzeugt wird, die entweder global wirklich oder "hinreichend" eindeutig ist.  

Wie werden im Hochschulabschlusszeugnis die Verweise auf weitere Dokumente verwaltet? HAZ verweist auf ToR und DS desselben Studienabschlusses. Es müssen also alle Dokumente im Block vorliegen. Wir planen eine GUID für den Studienabschluss zu vergeben und für die Einzeldokumente Suffixe zu GUID. Wäre das ok?

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. In den kommenden Arbeitskreisen werden wir diskutieren, ob und auf welche Weise technische IDs dieser Art überhaupt Teil von der XHS-Spezifikation sein sollten. 
Viele Grüße
Ihr Team von XHochschule

**Comment by init-xhochschule** [comment]
Update: Inzwischen gab es für die Version XHS 0.95 die folgende Änderung bzgl. der Thematik Dokument-ID (siehe Versionshistorie der aktuellen Spezifikation) https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf

III.E.1.3.3. Änderungen an der Verweisstruktur zwischen Dokumenten Für die Bildungsnachweise des Hochschulabschlusszeugnisses, des Diploma Supplement und des Transcript of Records wird zukünftig auf Datenfelder zum gegenseitigen Verweis und die Nutzung von xs:ID verzichtet. In das Hochschulabschlusszeugnis kann optional ein vollständiges Diploma Supplement integriert werden. Der Verweis auf das Transcript of Records innerhalb des Hochschulabschlusszeugnisses wird durch die direkte Angabe von Leistungen ersetzt.

Viele Grüße
Ihr Team von XHochschule
