### ISSUE TITLE
[S4Campus AG]: generierte Dokumente HAZ/EXMA

### ISSUE THREAD

**Issue by omueller-s4c** [OZG-TFBildung/XHochschule#48]
Autor: Oliver Müller
Art der Organisation: CaMS-Hersteller
Name des CaMS-Herstellers: S4Campus AG

Wie gestern besprochen finden Sie im Anhang die Dokumente zu Hochschulabschlusszeugnios und Exmatrikulationsbescheinigung, die wir aus dem System generiert haben.
[S4C_Tests.zip](https://github.com/OZG-TFBildung/XHochschule/files/10918655/S4C_Tests.zip)

**Comment by init-xhochschule** [comment]
Vielen Dank für die Bereitstellung Ihrer Dokumente. Für die Weiterentwicklung von XHochschule konnten wir daraus hilfreiche Rückschlüsse ziehen. 
Viele Grüße
Ihr Team von XHochschule
