### ISSUE TITLE
Stabilität der XSD für den Import möglich?

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#5]
Autor: Arn Waßmann
Art der Organisation: HIS Hochschul-Informations-System eG
Beschreibung: 

Guten Tag liebe Kolleginnen und Kollegen,

wir haben in einem Test in HISinOne die Version 0.4 implementiert und eine Studienbescheinigung nach §9 für das BAföG auszugsweise implementiert.

Dabei sind die folgenden Fragen für die Importseite entstanden:
- Wie stabil wird die XSD-Beschreibung für den Import? Welche Ideen / Vorstellungen gibt es zur Versionierung für die importierende Stelle? Die Hochschule hat bspw. aufgrund ihrer HISinOne-Version, die sie aktuell im Einsatz hat, die Version 1.1 im Einsatz. Das BAföG-Amt (oder wer auch immer die Nachricht entgegen nehmen wird) hat gerade ein Update bekommen und die Version 1.4 im Einsatz. Wird das kompatibel sein beim Import? Oder muss die importierende Stelle alle alten Versionen beherrschen?  Bei der großen Anzahl von externen Abhängigkeiten ist ein häufiger Versionswechsel (gesprochen wurde mal vielleicht 2x pro Jahr) wahrscheinlich. Wir haben aus dem XSD ein Java-Objektmodell erzeugt, dass aus 259 Dateien besteht. Da summiert sich mit der Zeit so einiges.
- Manche Nachrichten, bspw. für die Abschlussdokumente, werden erst Jahre nach der Erzeugung bei einer importierenden Stelle ankommen. Welche Pläne gibt es, dass ich mein digitales Abschlusszeugnis auch noch 5, 10, 20 oder 30 Jahre später in einem digitalen Prozess einreichen und verwenden kann? Sei es in Bewerbungsverfahren von Arbeitgebern oder weiterführenden Studiengängen?

Viele Grüße
Arn Waßmann

**Comment by XHochschuleDE** [comment]
Guten Tag Herr Waßmann,

wir bedanken uns bei Ihnen für Ihre Rückmeldung. Ihre aufgeworfenen Fragen werden in den kommenden Workshops besprochen.

Viele Grüße,
Oliver Budke

**Comment by XHochschuleDE** [comment]
@ArnWassmann Viele Antworten auf die von Ihnen aufgeworfenen Fragen werden Sie im Pflegekonzept und Implementierungshandbuch finden. In diesen beiden Dokumenten, die noch zu erarbeiten / veröffentlichen sind, wird es Vorgaben zu Aufwärts- und Abwärtskompatibilitäten von XHochschule geben.

Wir sehen es als Aufgabe von XHochschule an, dem Releasemanagement unterliegende Versionssprünge zu gewährleisten. Dadurch ist eine Vereinfachung für Implementierende zu erwarten, da eingebundene Schemata gekapselt und nicht mehr einzeln implementiert werden müssen. Bereits jetzt lässt sich sagen, dass Abwärtskompatibilität in kleinen Versionssprüngen (d.h. Minor-Releases) gewährleistet sein wird.

XHochschule arbeitet Änderungen stets so ein, dass wenige Releasewechsel entstehen. Tatsächlich denken wir, dass aufgrund sich ändernder Registerlandschaften, zunehmender Fachverfahrensvernetzung und des Datenaustauschs mit Europa und Sozialversicherungsträgern zweimal im Jahr Anpassungen an den Modellen erforderlich werden. Wir haben andere, einschlägige Vorhaben auf dem Radar und bringen uns im Interesse des deutschen Bildungswesen (Hochschulen sowie Ministerien) dort ein ([Europass](https://github.com/european-commission-europass/Europass-Learning-Model), [SDG](https://github.com/SEMICeu/SDG-sandbox), [XInneres](https://www1.osci.de/meldewesen/xmeld-2827)). Bedenken Sie bitte, dass durch XÖV Änderungen an Codelisten auch unterjährig stattfinden werden.
