### ISSUE TITLE
Enumerierte Codelisten - Pro und Contra 

### ISSUE THREAD

**Issue by mrhuber71** [OZG-TFBildung/XHochschule#50]
Creator: Mathias R. Huber; TU-Graz/CAMPUSonline
Type of the organisation: CAMS-Hersteller
Description: Frage und zu enumerierten Codelisten wie z.B. xhs:ArtDesHochschulabschlusses-Codes oder xhs:Studienbereich-Codes

Eine Listenreferenz ist gut (Attribute listURI und listVersionID):
``` XML
      <xhs:studienbereichDESTATIS listURI="urn:xhochschule-de:destatis:codeliste:studienbereich" listVersionID="WS22">
        <code>http://xhochschule.de/def/destatis/WS22/code/studienbereich/04</code>
      </xhs:studienbereichDESTATIS>
```

Eine starre Enumeration der erlaubten Codes würde bei jeder Listenänderung ein (ständiges) nachziehen des Schemas bedeuten.
Das bedeutet u.a. hohen Wartungsaufwand im XML-Schema. Eine alternative Lösung für eine Validierung wäre wünschenswert.

**Comment by init-xhochschule** [comment]
Vielen Dank für Ihren Hinweis. Uns ist bisher keine alternative Methode bekannt, die außerhalb im XML-Schema eine entsprechende Validierung der Inhalte ermöglicht. Wir sind jedoch offen für Hinweise.
Viele Grüße
Ihr Team von XHochschule

**Comment by mrhuber71** [comment]
_Wir sind jedoch offen für Hinweise._

Hinweis: Wie steht es mit der Schematron-Validierung?

Hier können Code-Listen(-XMLs) importiert werden und die Daten-XMLs können in Folge auf erlaubte Einträge laut Code-Listen-XML validiert werden.

Anbei ein kleines Beispiel, welches auf das wesentliche reduziert ist (ZIP-Datei)
- "codelist.xml" -> Code-Listen-XML
- "testdata.xml" -> Daten-XML
- "validate-code-within-codelist.sch" -> Schematron-Validierung für die Code-Liste im Daten-XML
- "validate-code-within-codelist-compiled.xsl" -> XSLT-Validierung für die Code-Liste im Daten-XML

[code-list-validation.zip](https://github.com/OZG-TFBildung/XHochschule/files/11204275/code-list-validation.zip)

**Comment by mrhuber71** [comment]
Hallo Team der XHochschule,

danke für ihre ausführliche Antwort mit deren Begründungen.

@ halbjährlicher Update-Zyklus ... am XML Schema ... **Mehraufwand** für Hersteller und Hochschulen
Ich denke, bei den CaMS-Herstellern und anderen Software-Herstellern wäre genau hier der Mehraufwand zu sehen.

Warum:
Codelisten müssen vermutlich in jedem Software-System auf die bereits intern vorhandenen Code-Listen gemapped werden. Diese sind oftmals tabellarisch verfügbar. Wären die Code-Listen in einfacher Art und Weise zu importieren (und nicht fix in einem Schema verdrahtet) kann eine Prüfung von ebenfalls gegen diese "Code-Import-Tabellen" erfolgen. Insofern das XML-Schema stabil bleibt (Unabhängig von potentiellen Schematron-Validierungen) hielte sich der Anpassungs- bzw. "Update-Aufwand" für die CaMS-Hersteller in Grenzen, denn bei Änderung der Code-Listen müssten diese importiert werden und "nur" das CaMS-interne Mapping adaptiert werden.
