### ISSUE TITLE
Frage zum Status des "Basis-Schemata" XBildung

### ISSUE THREAD

**Issue by mrhuber71** [OZG-TFBildung/XHochschule#51]
Autor: Mathias Huber; TU-Graz / CAMPUSonline
Art der Organisation: CAMS-Hersteller
Beschreibung: Basis-Typ "xbd:Document"

Inwieweit ist die Normierung von XBildung (bzw. XSchule) abgeschlossen? Beispielsweise kann das Element "xbd:titel" mehrfach angegeben auch mit gleichem Sprachverweis werden.
Zudem wäre es das Sprachattribut im Namespace "XBildung" abzubilden. (XML-Schema Datentyp xs:language)

``` XML
  <xbd:titel xml:lang="de-Latn-DE">asdf</xbd:titel>
  <xbd:titel xml:lang="de-Latn-DE">asdf</xbd:titel>
```

Geschmacksache ist zudem, ob ein XML-Element in einer Sequenz mit "minOccurs=0" und "maxOccurs='unbounded'" verpackt wird oder in eine Liste von "titles" gegeben wird. Hier könnte ebenfalls das Attribut "xbd:lang" als Unique definiert werden, insofern dies Sinn ergibt:

``` XML
  <xbd:titles>
    <xbd:titel xml:lang="de-Latn-DE">asdf</xbd:titel>
    <xbd:titel xml:lang="en">asdf</xbd:titel>
  </xbd:titles>
```

**Comment by init-xhochschule** [comment]
Update: Inzwischen gab es für die Version XHS 0.95 die folgenden Änderungen bzgl. der Mehrsprachigkeit (siehe Versionshistorie der aktuellen Spezifikation) https://xhochschule.de/def/xhochschule/0.95/spec/xhs_spezifikation_0.95.pdf

III.E.1.1.2. Umgang mit Mehrsprachigkeit
Mit dieser Version wird Mehrsprachigkeit nicht mehr auf Datenfeld-Ebene abgebildet. Muss das ganze Dokument in mehreren Sprachen vorliegen, wird davon ausgegangen, dass je Sprache ein XMLDokumente erstellt wird. Dieser Ansatz führt zu folgenden Änderungen: In der Klasse Dokument ist die Eigenschaft "sprache" nun verpflichtend (Häufigkeit 1, statt 0..n). Damit wird die Standard-Sprache des Dokuments festgelegt. Die Sprache eines Elements vom Typ xbd:String.Localized muss nur noch angegeben werden, wenn sie davon abweicht.

III.E.1.1.3. Häufigkeit bei xbd:String.Localized
Statt wie bisher Eigenschaften vom Typ xbd:String.Localized immer beliebig oft zu erlauben, um Mehrsprachigkeit abzubilden, sind sie nun nur so oft erlaubt, wie sie tatsächlich vorkommen dürfen. Daher wurde die Kardinalität der Eigenschaften vom Typ xbd:String.Localized in mehreren Klassen von 0..n auf 0..1 geändert.

Viele Grüße
Ihr Team von XHochschule
