### ISSUE TITLE
HIS eG: Rückmeldung zur 2. Pilotierung

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#52]
**Autor:** Arn Waßmann
**Art der Organisation:** HIS eG

**Upload von Beispieldokumenten**
Anbei eine Exmatrikulationsbescheinigung aus dem aktuellen Entwicklungsstand von HISinOne 2023.06. Es handelt sich um Beispieldaten. Auf dem PDF werden ein paar Platzhalter zur Bank nicht aufgelöst. Liegt vermutlich an den aktuellen Entwicklungen zum ePayment und spielt hier keine Rolle. 

Die PDF-Datei enthält eine XML-Datei gemäß XHEIE. Das XML ist signiert und enthält einen Verifikationscode.
 
[Exmatrikulationsbescheinigung.pdf](https://github.com/OZG-TFBildung/XHochschule/files/11017322/Exmatrikulationsbescheinigung.pdf)

**Comment by ArnWassmann** [comment]
Im aktuellen Entwicklungsstand von HISinOne 2023.06 ist auch die Gegenseite, also der Upload mit entsprechenden Auswertungen und Prüfungen implementiert. Es wäre sehr schön, wenn wir aus anderen CaMS erzeugte Exmatrikulationsbescheinigungen zum Testen erhalten könnten.
Vielen Dank!

**Comment by init-xhochschule** [comment]
Vielen Dank dafür. Auch weiterhin werden wir andere Hersteller dabei unterstützen XHS-Bescheinigungen zu Testzwecken im Rahmen der Pilotierung zu erstellen und zur Verfügung zu stellen.
Viele Grüße
Ihr Team von XHochschule
