### ISSUE TITLE
Bereitstellung der XML-Nachricht unklar

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XHochschule#6]
Autor: Arn Waßmann
Art der Organisation: HIS Hochschul-Informations-System eG
Beschreibung: 

Guten Tag liebe Kolleginnen und Kollegen,

wir haben in einem Experiment die Version 0.4 in HISinOne eingebaut, aus dem XSD mittels JAXB ein Java-Objekt erzeugt und auszugsweise mit Daten gefüllt.

Das ging mehr oder weniger gut. Eine große Herausforderung war dabei die vielen externen Abhängigkeiten in den Griff zu bekommen. Als Basis haben wir http://xhochschule.de/def/xhochschule/0.4/xsd/xhochschule-nachweis.xsd verwendet.

Aber wie geht es jetzt weiter? Leider wissen wir nicht was wir jetzt programmieren müssten.

Mein Kollege hat einen REST-Webservice erstellt mit dem man das XML abholen kann. Das ist zunächst eine sehr technische Lösung.
Man benötigt natürlich die Berechtigung dazu und eine gültige Authentifizierung für den Abruf. Auch kann man im fachlichen Prozess nicht zu jeder Zeit jeden Nachweis / Bescheid bekommen. Einen Imma-Bescheid gibt es bspw. erst, wenn es keine Hindernisse mehr gibt, wie bspw. die erfolgt Bezahlung oder einen gültigen Versicherungsstatus. So müsste das bei einem Webservice entsprechend auch berücksichtigt werden. Man könnte darüber nachdenken, bspw. mittels OAuth2 externen Systemen den Zugriff auf diesen Webservice zu ermöglichen.  Dann würde der Studierende die Freigabe und den Zugriff auf die Daten ermöglichen. Das funktioniert aber nicht in allen Szenarien von XHochschule. So will ich das Abschlusszeugnis bei mir haben, da ein Abruf von der Hochschule 5 Jahre nach der Exma wahrscheinlich nicht mehr möglich ist. Auch stellt sich die Frage wie man den Zugriff auf ältere Nachweise, bspw. aus dem Vorsemester, realisiert. Auch müssten alle Plattformen das so umsetzen. 

Ein anderer Vorschlag wäre daher, dass man die XML-Datei parallel zu den PDF-Dokumenten den Studierenden zur Verfügung stellt. Also ein Download, der analog zum PDF erzeugt wird. Damit würden die oben genannten Regeln berücksichtigt und für die Hochschule auf der Export-Seite kaum etwas ändern. Die Studierenden müssten sich dann selbst um Ihre Dateien und deren Aufbewahrung kümmern. Der große Nachteil besteht darin, dass nach aktuellem Stand der Spezifikation, eine XML-Datei zur Verfügung gestellt wird. Das werden die meisten Menschen nicht verstehen. Man könnte daher das XML in die bereits vorhandenen PDF-Dokumente einbetten. So kann ein Mensch die Daten verstehen und eine Maschine das Ganze auswerten.

Das technische Verfahren wird aber (nicht mehr) von XHochschule festgelegt. 

Welche Ideen gibt es noch für die importierende Seite? File-Upload für eine XML-Datei? Einbettung in ein PDF? Direkte Webservice-Abrufe zwischen den Systemen? Welche Protokolle? 

Ohne eine Festlegung wird es keinen Datenaustausch zwischen verschiedenen Plattformen geben können.

Viele Grüße
Arn Waßmann

**Comment by XHochschuleDE** [comment]
Guten Tag Herr Waßmann,

wir bedanken uns bei Ihnen für Ihre Rückmeldung. Die von aufgeworfenen Fragestellungen werden im Implementierungshandbuch behandelt werden (siehe Deliverable 3.4 "Handreichung Implementierungshandbuch an Entwickler für Pilotierung XHochschule"). Dieses Dokument ist noch zu erstellen.

Viele Grüße,
Oliver Budke

**Comment by HelmutHaimberger** [comment]
Guten Tag,

seitens der TU Graz/CAMPUSonline und den mit uns kooperierenden Hochschulen wurde zum Verfahren und dem Format für die Bereitstellung ebenfalls diskutiert.

Da für CAMPUSonline an einer Anbindung eines DMS gearbeitet wird, ist es notwendig, dass ein Format gefunden wird, das auch durch DMS unterstützt wird.
Insofern schließen wir uns dem Vorschlag von Herrn Waßmann an, da dieses Verfahren auch von manchen DMS unterstützt wird. Weiters bedeutet dies, dass in absehbarer Zeit entsprechende Anfragen von Bürger*innen, hinsichtlich der Bereitstellung von Dokumenten, von unseren kooperierenden Hochschulen nicht mehr durch CAMPUSonline bedient werden, sondern über ein DMS.

Beste Grüße,
Helmut Haimberger

**Comment by init-xhochschule** [comment]
Inzwischen hat sich herauskristallisiert, dass die Bereitstellung der XML Daten vorläufig mittels PDF mit integrierter XML-Datei erfolgen soll.  Die technischen Details dieser Bereitstellung werden noch genauer zu bestimmen sein, insbesondere durch die CaMS Hersteller selbst. Mehr Informationen dazu auch im Newsletter XHochschule vom 16.03.2022 https://xhochschule.de/web/XHSNewsletter2022-1
