### ISSUE TITLE
Ergänzungen im Informationsmodell

### ISSUE THREAD

**Issue by HolgerKlenke** [OZG-TFBildung/XHochschule#7]
Autor: Holger Klenke
Art der Organisation: HIS Hochschul-Informations-System eG
Beschreibung:  Ergänzungen im Informationsmodell

Guten Tag liebe Kolleginnen und Kollegen,

da zumindest die deutschen Hochschulen verpflichtet sind, Studierenden - und Prüfungsdaten an das jeweilige Statistische Landesamt zu melden, sollte das Informationsmodell mindestens die dazu notwendigen Daten beinhalten. Zusätzlich sind ggf. nicht für diesen Zweck zwingend notwendige Daten für den weiteren Prozess an einer aufnehmenden Hochschule hilfreich.

Viele Grüße
Holger Klenke

**Use Cases**

-  Hochschulwechsel: Student/-in in ist an Hochschule A  immatrikuliert und bewirbt sich an Hochschule B  
-  Neueinschreibung an anderer Hochschule: Student/-in war an Hochschule A  immatrikuliert (ist also exmatrikuliert) und bewirbt sich an Hochschule B  
-  Neueinschreibung an eigener Hochschule: Student/-in war an Hochschule A  immatrikuliert (ist also exmatrikuliert) und bewirbt sich erneut an Hochschule A (-> Abgleich zwischen vorhandenen Daten und zwischenzeitlichen Änderungen wie z. B.  hinzugekommenen Studienzeiten )
-  Parallel-Studium: Student/-in ist an Hochschule A als Haupthörer/-in in immatrikuliert und bewirbt sich an Hochschule B als Nebenhörer/-in
-  Kooperationsstudiengänge:  Daten-Abgleich zwischen den Kooperationshochschulen

**Ergänzungen im Informationsmodell**
Aus meiner Sicht fehlen im Informationsmodell folgende Informationen:

**Einschreibung**
* 	Hörerstatus 

**Studienperiode**
* 	Beginn und Ende der Studienperiode 

**Studienfach**
*  Regelstudienzeit 
*  Art des Studiums (Präsenzstudium, Fernstudium, Praxissemester ...)

**Studierende/r**
* 	Anzahl der Urlaubssemester
* 	Anzahl der Kollegsemester
* 	Anzahl der Unterbrechungssemester, Grund der Unterbrechung
* 	Anzahl der Praxissemester
* 	Hochschule der Ersteinschreibung in Deutschland
* 	Bei Ersteinschreibung im Ausland:  Land
* 	Semester der erstmaligen Einschreibung (an einer deutschen oder ausländischen)  Hochschule
* 	Erstes Semester an einer deutschen Hochschule
* 	Kennzeichen: Berufspraktische Tätigkeit vor dem Studium
* 	Studienbezogene Auslandsaufenthalte:
     - Auf welchen Studiengang (Abschluss und Fach)  bezog sich der Auslandsaufenthalt?
     - Staat
     - Dauer in Monaten
     - Art des Aufenthaltes  (Studium, Praktikum, …)
     - Art des Mobilitätsprogrammes (EU-Programm, Sonstiges öffentlich  gefördertes Programm, …)
     
* **Abgelegte Abschlussprüfungen an anderen Hochschulen sowie der ausstellenden Hochschule** 
     - Hochschule
     - Staat der Hochschule
     - Abschluss
     - _ 1. / 2. / 3. Studienfach
     - Monat und Jahr des Abschlusses
     - Ergebnis 
     - Gesamtnote
     
* **Erste Hochschulzugangsberechtigung (HZB)**
     - Art der HZB
     - Datum / Jahr des Erwerbs
     - Erwerb in Deutschland:  Kreis
     - Erwerb im Ausland:  Staat

**Comment by XHochschuleDE** [comment]
Guten Tag Herr Klenke,

wir bedanken uns bei Ihnen für Ihre Rückmeldung. Wir werden die von Ihnen vorgeschlagenen Ergänzungen im Informationsmodell prüfen und uns bei Ihnen zurückmelden.

Viele Grüße,
Oliver Budke

**Comment by XHochschuleDE** [comment]
@HolgerKlenke Vielen Dank für die Vorschläge. Eine Erweiterung des Use Case um das komplexe Thema Statistik müsste mit den Bedarfsträgern von XHochschule / XBildung geprüft werden. Die Nachnutzung von durch DESTATIS herausgegebenen Wertelisten ist jedoch bereits in der vorliegenden Version umgesetzt. Diese Listen sind

https://github.com/OZG-TFBildung/XHochschule/blob/070cf2308a1d0689eca6301169459a9d8227c95b/code/urn-xhochschule-de-destatis-codeliste-faecherschluessel_0.4.xml
https://github.com/OZG-TFBildung/XHochschule/blob/070cf2308a1d0689eca6301169459a9d8227c95b/code/urn-xhochschule-de-destatis-codeliste-hochschulsignatur_0.4.xml
https://github.com/OZG-TFBildung/XHochschule/blob/070cf2308a1d0689eca6301169459a9d8227c95b/code/urn-xhochschule-de-destatis-codeliste-studienbereich_0.4.xml

**Comment by init-xhochschule** [comment]
Guten Tag. In der aktuellen Version 0.92 von XHochschule verfolgen wir den Ansatz nur solche statistischen Werte nachzunutzen, die den fachlichen Datenaustausch relevant sind, z.B. beim Studienplatzwechsel. Statistikmeldungen der einzelnen Hochschulen an sich sind jedoch derzeit out of scope von XHochschule.
