### ISSUE TITLE
Exmatrikulationsbescheinigung als Nachricht

### ISSUE THREAD

**Issue by HolgerKlenke** [OZG-TFBildung/XHochschule#8]
Autor: Holger Klenke
Art der Organisation: HIS Hochschul-Informations-System eG
Beschreibung:  Exmatrikulationsbescheinigung als Nachricht

Guten Tag liebe Kolleginnen und Kollegen,

Bezug nehmend auf  https://github.com/OZG-TFBildung/XHochschule/issues/7 fehlt aus meiner Sicht im Abschnitt 

             Datenübermittlung zwischen Kommunikationspartnern > Nachweis > Die Nachrichten

noch als Nachricht die Exmatrikulationsbescheinigung, da sich sowohl exmatrikulierte als auch noch immatrikulierte Studierende bewerben können. Die Exmatrikulationsbescheinigung/-nachricht sollte neben den exmatrikulationsspezifischen Daten auch die (erweiterten) Daten des Informationsmodells enthalten (ein/e Studierende/r war ja unmittelbar VOR der Exmatrikulation an der ausstellenden Hochschule immatrikuliert).

Viele Grüße und schöne Pfingsttage
Holger Klenke

**Comment by XHochschuleDE** [comment]
Guten Tag Herr Klenke,

wir bedanken uns bei Ihnen für Ihre Rückmeldung. Wir werden die von Ihnen vorgeschlagene Ergänzung der Nachweis-Nachrichten um die Exmatrikulationsbescheinigung prüfen und uns hier zurückmelden.

Viele Grüße,
Oliver Budke

**Comment by XHochschuleDE** [comment]
@HolgerKlenke Im Webmeeting III haben wir die Erweiterung von XHochschule um die Exmatrikulationsbescheinigung angekündigt. Die beim IT-Planungsrat eingereichte Bedarfsbeschreibung führt die Exmatrikulationsbeschreibung als Nachweis mit Digitialisierungspotenzial für die Spezifikation an: https://www.it-planungsrat.de/SharedDocs/Downloads/DE/Entscheidungen/33_Sitzung/TOP11_AL1_Datenaustausch_im_Hochschulwesen_Bedarfsbeschreibung.pdf;jsessionid=DBBA5ADB78B2730B425A2A9577A7EFE7.2_cid340?__blob=publicationFile&v=2 , S. 22

Die Modellierung einer zugehörigen Nachricht ist also eingeplant und wird Teil einer zukünftigen Version von XHochschule.
